async function loadModule() {
    const module = await import('./functions.js');
    // Use the imported module
    await import('./getways_api/getways_api.js');
    await import('./CronJob/transaction.js')
    await import('./CronJob/totalLiquorCron.js')
    await import('./Triggers/triggers.js')
    await import('./Triggers/nowPayment.js')
    await import('./Triggers/transfiPayment.js')
    await import('./Triggers/WalletAddress.js')
    await import('./ScInputData/generateInput.js')
    await import('./WalletProcessing/wallet.js')
    await import('./BSCSCAN/api.js')
    await import('./CoinBaseOnRamp/CoinBase.js')
    await import('./parse.js')
    await import('./Triggers/transaction.js')
    await import('./PayArc/payarc.js')
    await import('./Stripe/stripeCheckout.js')
    await import('./Stripe/totalLiquorCheckout.js')
    await import('./PlarformService/PlatformService.js')
    await import('./paynearme.js')
    await import('./click.js')
    await import('./CronJob/email.js')
    await import('./Fiserv/FiservPayment.js')
    await import('./Fiserv/FiservCheckout.js')
    await import('./Fiserv/FiservDigitalDisbursements.js')
    await import('./Triggers/user.js')
    await import('./AuthorizeNet.js')
    await import('./payoutAPI.js')
    await import('./cellpay.js')
    await import('./Fiserv/CommerceHub/CommerceHubHostedPages.js')
    await import('./Fiserv/CommerceHub/CommerceHubHostedComponents.js')
    await import('./Fiserv/CommerceHub/CommerceHubHostedFields.js')
    await import('./Fiserv/CommerceHub/AffirmHostedCheckout.js')
    await import('./Fiserv/CommerceHub/PazeHostedCheckout.js')
    await import('./Seon.js')
    await import('./FinixPayment.js')
}

loadModule();