name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: getways-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH to EC2 and pull latest code
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/html/Production/getways-server
          # Pull the latest code using your configured deploy key
          sudo -E env "GIT_SSH_COMMAND=ssh -i ~/.ssh/id_rsa" git pull origin master
          # Install dependencies
          sudo npm install
          # Restart the app
          pm2 restart all || pm2 start index.js --name "getways-server"
        EOF
